version: '2'

services:
  building:
    build: .
    volumes:
      - .:/app
    working_dir: /app/VisitPath
    command: /bin/bash -c "npm install && dotnet restore && dotnet build && dotnet publish -c Release -o ./obj/Docker/publish"