
FROM microsoft/aspnetcore-build
ARG source=.
WORKDIR /app
ADD . $source
WORKDIR /app/VisitPath
RUN ["npm", "i"]
WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
WORKDIR /app/VisitPath
COPY ./VisitPath/webpack.config.js .
COPY ./VisitPath/webpack.config.vendor.js .
ENTRYPOINT [ "dotnet","publish", "VisitPath.csproj", "-o ./obj/Docker/publish" ]