
FROM microsoft/aspnetcore-build
ARG source=.
WORKDIR /app
ADD . $source
WORKDIR /app/VisitPath
RUN ["npm", "i"]
WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
WORKDIR /app/VisitPath
ENTRYPOINT [ "dotnet","publish", "VisitPath.csproj", "-c Release", "-o ./obj/Docker/publish" ]
